// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQKipPc_LT2qywt1nkk6hP9MQ3KT9nOew',
    appId: '1:78782712918:web:bf63036f3fd70d305cfff7',
    messagingSenderId: '78782712918',
    projectId: 'house-of-tasty-e7857',
    authDomain: 'house-of-tasty-e7857.firebaseapp.com',
    storageBucket: 'house-of-tasty-e7857.appspot.com',
    measurementId: 'G-4WTQ6GQYVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0oaJcptCy_lXJaU1hpHNZJcQ3DbOHX74',
    appId: '1:78782712918:android:22a9fcff8f71b7bd5cfff7',
    messagingSenderId: '78782712918',
    projectId: 'house-of-tasty-e7857',
    storageBucket: 'house-of-tasty-e7857.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZwQuRtw08FBenXKx4RUFpq8dWeAWpQ0c',
    appId: '1:78782712918:ios:0ac55aa4abb20d095cfff7',
    messagingSenderId: '78782712918',
    projectId: 'house-of-tasty-e7857',
    storageBucket: 'house-of-tasty-e7857.appspot.com',
    iosBundleId: 'com.example.houseOfTasty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZwQuRtw08FBenXKx4RUFpq8dWeAWpQ0c',
    appId: '1:78782712918:ios:71703d782f85d8a25cfff7',
    messagingSenderId: '78782712918',
    projectId: 'house-of-tasty-e7857',
    storageBucket: 'house-of-tasty-e7857.appspot.com',
    iosBundleId: 'com.example.houseOfTasty.RunnerTests',
  );
}
